//===- ELFWrapper.cpp - ELF 加壳工具（集成到 clang driver）-----------===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// 本文件实现 ELF 可执行文件加壳功能，直接编译进 clang.exe：
// 1. 读取原始 ELF 文件
// 2. 使用 ChaCha20 加密
// 3. 生成 payload.h (C 头文件，包含加密后的字节数组)
// 4. 生成 loader.cpp 壳源码
// 5. 调用 clang 自身编译壳程序（最高强度混淆）
// 6. 替换输出为加壳后的可执行文件
//
//===----------------------------------------------------------------------===//

#include "clang/Driver/ELFWrapper.h"
#include "clang/Driver/Driver.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Compression.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/raw_ostream.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <fstream>
#include <random>

using namespace llvm;
using namespace clang::driver;

// ============================================================================
// ChaCha20 实现
// ============================================================================

static inline uint32_t rotl32(uint32_t v, int n) {
  return (v << n) | (v >> (32 - n));
}

static inline void qr(uint32_t *s, int a, int b, int c, int d) {
  s[a] += s[b]; s[d] ^= s[a]; s[d] = rotl32(s[d], 16);
  s[c] += s[d]; s[b] ^= s[c]; s[b] = rotl32(s[b], 12);
  s[a] += s[b]; s[d] ^= s[a]; s[d] = rotl32(s[d], 8);
  s[c] += s[d]; s[b] ^= s[c]; s[b] = rotl32(s[b], 7);
}

static void chacha20_block(const uint32_t key[8], uint32_t counter,
                           const uint32_t nonce[3], uint8_t out[64]) {
  uint32_t s[16] = {
      0x61707865, 0x3320646e, 0x79622d32, 0x6b206574,
      key[0], key[1], key[2], key[3],
      key[4], key[5], key[6], key[7],
      counter,
      nonce[0], nonce[1], nonce[2]};

  uint32_t w[16];
  memcpy(w, s, sizeof(w));

  for (int i = 0; i < 10; i++) {
    qr(w, 0, 4, 8, 12);
    qr(w, 1, 5, 9, 13);
    qr(w, 2, 6, 10, 14);
    qr(w, 3, 7, 11, 15);
    qr(w, 0, 5, 10, 15);
    qr(w, 1, 6, 11, 12);
    qr(w, 2, 7, 8, 13);
    qr(w, 3, 4, 9, 14);
  }

  for (int i = 0; i < 16; i++) {
    uint32_t val = w[i] + s[i];
    out[i * 4 + 0] = (uint8_t)(val);
    out[i * 4 + 1] = (uint8_t)(val >> 8);
    out[i * 4 + 2] = (uint8_t)(val >> 16);
    out[i * 4 + 3] = (uint8_t)(val >> 24);
  }
}

static size_t chacha20_encrypt(const uint8_t *input, size_t input_len,
                               const uint8_t key[32], const uint8_t nonce[12],
                               uint8_t *output) {
  uint32_t k[8], n[3];
  for (int i = 0; i < 8; i++)
    k[i] = (uint32_t)key[i * 4] | ((uint32_t)key[i * 4 + 1] << 8) |
           ((uint32_t)key[i * 4 + 2] << 16) | ((uint32_t)key[i * 4 + 3] << 24);
  for (int i = 0; i < 3; i++)
    n[i] = (uint32_t)nonce[i * 4] | ((uint32_t)nonce[i * 4 + 1] << 8) |
           ((uint32_t)nonce[i * 4 + 2] << 16) | ((uint32_t)nonce[i * 4 + 3] << 24);

  uint32_t counter = 1;
  uint8_t keystream[64];
  size_t offset = 0;

  while (offset < input_len) {
    chacha20_block(k, counter++, n, keystream);
    size_t chunk = (input_len - offset > 64) ? 64 : (input_len - offset);
    for (size_t i = 0; i < chunk; i++)
      output[offset + i] = input[offset + i] ^ keystream[i];
    offset += chunk;
  }
  return offset;
}

// ============================================================================
// 生成随机密钥
// ============================================================================

static void generate_random_key(uint8_t key[32], uint8_t nonce[12]) {
  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_int_distribution<uint32_t> dist(0, 255);
  for (int i = 0; i < 32; i++) key[i] = dist(gen);
  for (int i = 0; i < 12; i++) nonce[i] = dist(gen);
}

// ============================================================================
// 生成 payload.h
// ============================================================================

static bool generatePayloadH(const std::string &output_path,
                              const uint8_t *encrypted_data, size_t encrypted_size,
                              const uint8_t key[32], const uint8_t nonce[12],
                              const std::string &env_key) {
  std::error_code EC;
  raw_fd_ostream OS(output_path, EC, sys::fs::OF_None);
  if (EC) {
    errs() << "Error: Cannot write payload.h: " << EC.message() << "\n";
    return false;
  }

  OS << "/*\n";
  OS << " * ChaCha20 encrypted payload - auto generated by clang -irobf-linker\n";
  OS << " * Original size: " << encrypted_size << " bytes\n";
  OS << " */\n\n";
  OS << "#ifndef PAYLOAD_H\n";
  OS << "#define PAYLOAD_H\n\n";
  OS << "#include <stdint.h>\n";
  OS << "#include <stddef.h>\n\n";
  OS << "#define PAYLOAD_RAW_SIZE " << encrypted_size << "u\n\n";

  OS << "#define CHACHA20_KEY {";
  for (int i = 0; i < 32; i++) {
    OS << "0x" << format_hex_no_prefix(key[i], 2);
    if (i < 31) OS << ",";
  }
  OS << "}\n\n";

  OS << "#define CHACHA20_NONCE {";
  for (int i = 0; i < 12; i++) {
    OS << "0x" << format_hex_no_prefix(nonce[i], 2);
    if (i < 11) OS << ",";
  }
  OS << "}\n\n";

  OS << "static const uint8_t payload_data[] = {\n";
  for (size_t i = 0; i < encrypted_size; i++) {
    if (i % 16 == 0) OS << "    ";
    OS << "0x" << format_hex_no_prefix(encrypted_data[i], 2);
    if (i < encrypted_size - 1) OS << ", ";
    if (i % 16 == 15 || i == encrypted_size - 1) OS << "\n";
  }
  OS << "};\n";
  OS << "static const size_t payload_data_size = " << encrypted_size << ";\n\n";

  // 环境变量密钥（壳程序设置 lc=<env_key>，内嵌检测代码校验）
  OS << "#define ENV_KEY \"" << env_key << "\"\n\n";

  OS << "#endif // PAYLOAD_H\n";
  OS.flush();
  return true;
}

// ============================================================================
// 生成 loader.cpp 壳源码
// ============================================================================

static bool generateLoaderCpp(const std::string &output_path, bool DebugMode,
                              bool UseAsmTrampoline) {
  std::error_code EC;
  raw_fd_ostream OS(output_path, EC, sys::fs::OF_None);
  if (EC) {
    errs() << "Error: Cannot write loader.cpp: " << EC.message() << "\n";
    return false;
  }

  OS << R"(/*
 * ARM64 ELF 内存加载器 - ChaCha20 解密 + fork 执行 + 擦除 ELF 头 + 反调试
 * 自动生成，由 clang -irobf-linker 产生
 */

#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

#include <elf.h>
#include <sys/mman.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/ptrace.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <dlfcn.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <pthread.h>
#include <android/log.h>

#include "payload.h"

#define LOG_TAG "ELFLoader"
#define IROBF_LINKER_DEBUG )";
  OS << (DebugMode ? "1" : "0");
  OS << R"(

#ifndef MFD_CLOEXEC
#define MFD_CLOEXEC 0x0001U
#endif

#ifndef AT_EMPTY_PATH
#define AT_EMPTY_PATH 0x1000
#endif

extern char** environ;

#if IROBF_LINKER_DEBUG
static void debug_log(const char* msg) {
    if (msg) write(2, msg, strlen(msg));
}

static void debug_log_errno(const char* prefix) {
    char buf[256];
    int e = errno;
    int n = snprintf(buf, sizeof(buf), "%s errno=%d\n", prefix, e);
    if (n > 0) write(2, buf, (size_t)n);
}
#else
static void debug_log(const char* msg) { (void)msg; }
static void debug_log_errno(const char* prefix) { (void)prefix; }
#endif

#define IROBF_PAGE_SIZE 4096UL
#define IROBF_ALIGN_MASK (IROBF_PAGE_SIZE - 1)
#define ROUND_PG(x) (((x) + IROBF_ALIGN_MASK) & ~IROBF_ALIGN_MASK)
#define TRUNC_PG(x) ((x) & ~IROBF_ALIGN_MASK)
#define PFLAGS(x) ((((x) & PF_R) ? PROT_READ : 0) | \
                   (((x) & PF_W) ? PROT_WRITE : 0) | \
                   (((x) & PF_X) ? PROT_EXEC : 0))
#define LOAD_ERR ((unsigned long)-1)

extern "C" void trampo_jump(unsigned long entry, unsigned long *stack);

static inline uint32_t rotl32(uint32_t v, int n) {
    return (v << n) | (v >> (32 - n));
}

static inline void qr(uint32_t* s, int a, int b, int c, int d) {
    s[a] += s[b]; s[d] ^= s[a]; s[d] = rotl32(s[d], 16);
    s[c] += s[d]; s[b] ^= s[c]; s[b] = rotl32(s[b], 12);
    s[a] += s[b]; s[d] ^= s[a]; s[d] = rotl32(s[d], 8);
    s[c] += s[d]; s[b] ^= s[c]; s[b] = rotl32(s[b], 7);
}

static void chacha20_block(const uint32_t key[8], uint32_t counter,
                           const uint32_t nonce[3], uint8_t out[64]) {
    uint32_t s[16] = {
        0x61707865, 0x3320646e, 0x79622d32, 0x6b206574,
        key[0], key[1], key[2], key[3],
        key[4], key[5], key[6], key[7],
        counter, nonce[0], nonce[1], nonce[2]
    };
    uint32_t w[16];
    memcpy(w, s, sizeof(w));
    for (int i = 0; i < 10; i++) {
        qr(w, 0, 4,  8, 12); qr(w, 1, 5,  9, 13);
        qr(w, 2, 6, 10, 14); qr(w, 3, 7, 11, 15);
        qr(w, 0, 5, 10, 15); qr(w, 1, 6, 11, 12);
        qr(w, 2, 7,  8, 13); qr(w, 3, 4,  9, 14);
    }
    for (int i = 0; i < 16; i++) {
        uint32_t val = w[i] + s[i];
        out[i*4+0]=(uint8_t)(val); out[i*4+1]=(uint8_t)(val>>8);
        out[i*4+2]=(uint8_t)(val>>16); out[i*4+3]=(uint8_t)(val>>24);
    }
}

static size_t chacha20_decrypt(const uint8_t* input, size_t input_len,
                               const uint8_t key[32], const uint8_t nonce[12],
                               uint8_t* output) {
    uint32_t k[8], n[3];
    for (int i = 0; i < 8; i++)
        k[i] = (uint32_t)key[i*4]|((uint32_t)key[i*4+1]<<8)|((uint32_t)key[i*4+2]<<16)|((uint32_t)key[i*4+3]<<24);
    for (int i = 0; i < 3; i++)
        n[i] = (uint32_t)nonce[i*4]|((uint32_t)nonce[i*4+1]<<8)|((uint32_t)nonce[i*4+2]<<16)|((uint32_t)nonce[i*4+3]<<24);
    uint32_t counter = 1;
    uint8_t keystream[64];
    size_t offset = 0;
    while (offset < input_len) {
        chacha20_block(k, counter++, n, keystream);
        size_t chunk = (input_len - offset > 64) ? 64 : (input_len - offset);
        for (size_t i = 0; i < chunk; i++)
            output[offset + i] = input[offset + i] ^ keystream[i];
        offset += chunk;
    }
    return offset;
}

// ============================================================================
// 反调试：读取指定进程的 TracerPid
// ============================================================================
static pid_t get_tracerpid_of(pid_t pid) {
    char path[64];
    snprintf(path, sizeof(path), "/proc/%d/status", pid);
    int fd = open(path, O_RDONLY);
    if (fd < 0) return -1;
    char buf[4096];
    ssize_t n = read(fd, buf, sizeof(buf) - 1);
    close(fd);
    if (n <= 0) return -1;
    buf[n] = '\0';
    const char* tag = "TracerPid:\t";
    char* p = strstr(buf, tag);
    if (!p) return -1;
    p += strlen(tag);
    return (pid_t)atoi(p);
}

// ============================================================================
// 反调试：父进程作为 tracer 持续监控子进程
// 子进程 execv 前调用 PTRACE_TRACEME，exec 后 trace 关系保持
// 外部进程无法再 ptrace 附加子进程
// ============================================================================
static void* anti_debug_thread(void* arg) {
    pid_t child = *(pid_t*)arg;

    for (;;) {
        // 检测子进程的 TracerPid
        // 正常情况：TracerPid == 父进程 PID（我们正在 trace 它）
        // 异常情况：TracerPid == 0（trace 关系被断开，被反调试绕过）
        pid_t tracer = get_tracerpid_of(child);
        if (tracer == 0) {
            // TracerPid 为 0：trace 关系被断开，杀掉子进程
            kill(child, SIGKILL);
            _exit(9);
        }
        usleep(200000);
    }
    return NULL;
}

// ============================================================================
// 手工 ELF 加载
// ============================================================================
static int check_ehdr(Elf64_Ehdr *ehdr) {
    unsigned char *e = ehdr->e_ident;
    return (e[EI_MAG0] == ELFMAG0 &&
            e[EI_MAG1] == ELFMAG1 &&
            e[EI_MAG2] == ELFMAG2 &&
            e[EI_MAG3] == ELFMAG3 &&
            e[EI_CLASS] == ELFCLASS64 &&
            e[EI_VERSION] == EV_CURRENT &&
            (ehdr->e_type == ET_EXEC || ehdr->e_type == ET_DYN));
}

static unsigned long loadelf_mem(unsigned char *data, size_t data_sz,
                                 Elf64_Ehdr *ehdr, Elf64_Phdr *phdr) {
    unsigned long minva = (unsigned long)-1, maxva = 0;
    int dyn = (ehdr->e_type == ET_DYN);
    for (int i = 0; i < ehdr->e_phnum; i++) {
        if (phdr[i].p_type != PT_LOAD) continue;
        if (phdr[i].p_offset + phdr[i].p_filesz > data_sz) return LOAD_ERR;
        if (phdr[i].p_vaddr < minva) minva = phdr[i].p_vaddr;
        if (phdr[i].p_vaddr + phdr[i].p_memsz > maxva)
            maxva = phdr[i].p_vaddr + phdr[i].p_memsz;
    }
    if (minva == (unsigned long)-1) return LOAD_ERR;

    minva = TRUNC_PG(minva);
    maxva = ROUND_PG(maxva);
    int flags = (dyn ? 0 : MAP_FIXED) | MAP_PRIVATE | MAP_ANONYMOUS;
    unsigned char *base = (unsigned char*)mmap(
        dyn ? NULL : (void*)minva, maxva - minva, PROT_NONE, flags, -1, 0);
    if (base == MAP_FAILED) return LOAD_ERR;
    munmap(base, maxva - minva);

    flags = MAP_FIXED | MAP_ANONYMOUS | MAP_PRIVATE;
    for (int i = 0; i < ehdr->e_phnum; i++) {
        if (phdr[i].p_type != PT_LOAD) continue;
        unsigned long off = phdr[i].p_vaddr & IROBF_ALIGN_MASK;
        unsigned long start =
            (dyn ? (unsigned long)base : 0) + TRUNC_PG(phdr[i].p_vaddr);
        size_t segsz = ROUND_PG(phdr[i].p_memsz + off);
        unsigned char *p = (unsigned char*)mmap(
            (void*)start, segsz, PROT_WRITE, flags, -1, 0);
        if (p == MAP_FAILED) return LOAD_ERR;
        memcpy(p + off, data + phdr[i].p_offset, phdr[i].p_filesz);
        if (phdr[i].p_memsz > phdr[i].p_filesz)
            memset(p + off + phdr[i].p_filesz, 0,
                   phdr[i].p_memsz - phdr[i].p_filesz);
        int prot = PFLAGS(phdr[i].p_flags);
        if (mprotect(p, segsz, prot) < 0) return LOAD_ERR;
    }
    return (unsigned long)base;
}

static void rewrite_auxv(char **argv, char **envp, Elf64_Ehdr *ehdr,
                         unsigned long base, unsigned long entry) {
    char **p = envp;
    while (*p++ != NULL) {}
    Elf64_auxv_t *av = (Elf64_auxv_t*)p;
    while (av->a_type != AT_NULL) {
        switch (av->a_type) {
            case AT_PHDR:
                av->a_un.a_val = base + ehdr->e_phoff;
                break;
            case AT_PHNUM:
                av->a_un.a_val = ehdr->e_phnum;
                break;
            case AT_PHENT:
                av->a_un.a_val = ehdr->e_phentsize;
                break;
            case AT_ENTRY:
                av->a_un.a_val = entry;
                break;
            case AT_BASE:
                av->a_un.a_val = (ehdr->e_type == ET_DYN) ? base : 0;
                break;
            case AT_EXECFN:
                if (argv && argv[0])
                    av->a_un.a_val = (unsigned long)argv[0];
                break;
        }
        av++;
    }
}

static bool requires_kernel_elf_loader(Elf64_Ehdr *ehdr, Elf64_Phdr *phdr) {
    for (int i = 0; i < ehdr->e_phnum; i++) {
        if (phdr[i].p_type == PT_INTERP || phdr[i].p_type == PT_DYNAMIC)
            return true;
    }
    return false;
}

static ssize_t write_all(int fd, const uint8_t* data, size_t size) {
    size_t written = 0;
    while (written < size) {
        ssize_t n = write(fd, data + written, size - written);
        if (n < 0) {
            if (errno == EINTR) continue;
            return -1;
        }
        if (n == 0) return -1;
        written += (size_t)n;
    }
    return (ssize_t)written;
}

static int create_exec_fd(void) {
#ifdef __NR_memfd_create
    return syscall(__NR_memfd_create, "ap_ld_mem", MFD_CLOEXEC);
#else
    errno = ENOSYS;
    return -1;
#endif
}

static int exec_loaded_image(int exec_fd, char** argv) {
#ifdef __NR_execveat
    syscall(__NR_execveat, exec_fd, "", argv, environ, AT_EMPTY_PATH);
    if (errno != ENOSYS) return -1;
#endif
    char proc_path[64];
    snprintf(proc_path, sizeof(proc_path), "/proc/self/fd/%d", exec_fd);
    execve(proc_path, argv, environ);
    return -1;
}

static uint8_t *g_decrypted_image = NULL;
static size_t g_decrypted_size = 0;
static int g_exec_fd = -1;
static int g_use_kernel_loader = 0;
static pid_t g_child_pid = -1;
static char g_env_key[33] = {};

static bool do_load(const uint8_t* encrypted_data, size_t encrypted_size) {
    debug_log("[irobf-linker] do_load begin\n");
    uint8_t* decrypted = (uint8_t*)malloc(encrypted_size);
    if (!decrypted) return false;
    const uint8_t key[] = CHACHA20_KEY;
    const uint8_t nonce[] = CHACHA20_NONCE;
    chacha20_decrypt(encrypted_data, encrypted_size, key, nonce, decrypted);

    Elf64_Ehdr *ehdr = (Elf64_Ehdr*)decrypted;
    if (!check_ehdr(ehdr)) {
        debug_log("[irobf-linker] invalid decrypted elf\n");
        memset(decrypted, 0, encrypted_size);
        free(decrypted);
        return false;
    }

    Elf64_Phdr *phdr = (Elf64_Phdr*)(decrypted + ehdr->e_phoff);
    g_use_kernel_loader = requires_kernel_elf_loader(ehdr, phdr) ? 1 : 0;
    if (g_use_kernel_loader) {
        debug_log("[irobf-linker] dynamic elf -> memfd path\n");
        int fd = create_exec_fd();
        if (fd < 0) {
            debug_log_errno("[irobf-linker] memfd_create failed");
            memset(decrypted, 0, encrypted_size);
            free(decrypted);
            return false;
        }
        if (write_all(fd, decrypted, encrypted_size) != (ssize_t)encrypted_size ||
            lseek(fd, 0, SEEK_SET) < 0) {
            debug_log_errno("[irobf-linker] write memfd failed");
            close(fd);
            memset(decrypted, 0, encrypted_size);
            free(decrypted);
            return false;
        }
        memset(decrypted, 0, encrypted_size);
        free(decrypted);
        g_exec_fd = fd;
        g_decrypted_image = NULL;
        g_decrypted_size = 0;
        debug_log("[irobf-linker] memfd ready\n");
        return true;
    }

    debug_log("[irobf-linker] simple elf -> manual map path\n");
    g_decrypted_image = decrypted;
    g_decrypted_size = encrypted_size;
    debug_log("[irobf-linker] do_load ok\n");
    return true;
}

static int do_execute(int argc, char** argv, char** envp) {
    if (!g_use_kernel_loader && (!g_decrypted_image || g_decrypted_size == 0))
        return -1;
    if (g_use_kernel_loader && g_exec_fd < 0)
        return -1;
    debug_log("[irobf-linker] fork child\n");
    pid_t pid = fork();
    if (pid < 0) return -1;
    if (pid == 0) {
        prctl(PR_SET_DUMPABLE, 0);
        setenv("lc", g_env_key, 1);

        if (g_use_kernel_loader) {
            debug_log("[irobf-linker] exec memfd path\n");
            exec_loaded_image(g_exec_fd, argv);
            debug_log_errno("[irobf-linker] exec memfd failed");
            _exit(127);
        }

        Elf64_Ehdr *ehdr = (Elf64_Ehdr*)g_decrypted_image;
        Elf64_Phdr *phdr = (Elf64_Phdr*)(g_decrypted_image + ehdr->e_phoff);
        unsigned long base = loadelf_mem(g_decrypted_image, g_decrypted_size,
                                         ehdr, phdr);
        if (base == LOAD_ERR) {
            debug_log_errno("[irobf-linker] loadelf_mem failed");
            _exit(127);
        }

        unsigned long entry =
            ehdr->e_entry + (ehdr->e_type == ET_DYN ? base : 0);
        rewrite_auxv(argv, envp, ehdr, base, entry);
        memset(g_decrypted_image, 0, g_decrypted_size);
        free(g_decrypted_image);
        g_decrypted_image = NULL;
        g_decrypted_size = 0;
        debug_log("[irobf-linker] trampo jump\n");

        unsigned long *sp = (unsigned long*)argv - 1;
        sp[0] = (unsigned long)argc;
        trampo_jump(entry, sp);
        _exit(127);
    }
    g_child_pid = pid;
    int status = 0;
    waitpid(pid, &status, 0);
    if (WIFEXITED(status)) {
        char buf[96];
        int n = snprintf(buf, sizeof(buf),
                         "[irobf-linker] child exit=%d\n", WEXITSTATUS(status));
        if (n > 0) debug_log(buf);
        return WEXITSTATUS(status);
    }
    if (WIFSIGNALED(status)) {
        char buf[96];
        int n = snprintf(buf, sizeof(buf),
                         "[irobf-linker] child signal=%d\n", WTERMSIG(status));
        if (n > 0) debug_log(buf);
        return -WTERMSIG(status);
    }
    return -1;
}

extern "C" int irobf_loader_entry(int argc, char* argv[], char* envp[]) {
    // 初始化环境变量密钥
    const char* ek = ENV_KEY;
    strncpy(g_env_key, ek, sizeof(g_env_key) - 1);
    g_env_key[sizeof(g_env_key) - 1] = '\0';

    if (!do_load(payload_data, payload_data_size)) return 1;
    int result = do_execute(argc, argv, envp);
    if (g_decrypted_image) {
        memset(g_decrypted_image, 0, g_decrypted_size);
        free(g_decrypted_image);
        g_decrypted_image = NULL;
        g_decrypted_size = 0;
    }
    if (g_exec_fd >= 0) {
        close(g_exec_fd);
        g_exec_fd = -1;
    }
    g_use_kernel_loader = 0;
    return result;
}

)";
  if (!UseAsmTrampoline) {
    OS << R"(
int main(int argc, char* argv[]) {
    return irobf_loader_entry(argc, argv, environ);
}
)";
  }
  OS << R"()";
  OS.flush();
  return true;
}

// ============================================================================
// 生成 loader.S 壳入口跳板
// ============================================================================

static bool generateLoaderAsm(const std::string &output_path,
                              StringRef TargetTriple) {
  std::error_code EC;
  raw_fd_ostream OS(output_path, EC, sys::fs::OF_None);
  if (EC) {
    errs() << "Error: Cannot write loader.S: " << EC.message() << "\n";
    return false;
  }

  if (TargetTriple.starts_with("aarch64")) {
    OS << R"(.text
.globl _start
.type _start, %function
.globl trampo_jump
.type trampo_jump, %function
.extern irobf_loader_entry
_start:
    mov x29, xzr
    mov x30, xzr
    ldr x0, [sp]
    add x1, sp, #8
    add x2, x1, x0, lsl #3
    add x2, x2, #8
    bl irobf_loader_entry
    mov x8, #93
    svc #0
    b .
.size _start, . - _start
trampo_jump:
    mov sp, x1
    br x0
.size trampo_jump, . - trampo_jump
.section .note.GNU-stack,"",%progbits
)";
  } else {
    errs() << "Error: [irobf-linker] loader.S trampoline only supports aarch64 currently\n";
    return false;
  }

  OS.flush();
  return true;
}

// ============================================================================
// 执行 ELF 加壳
// ============================================================================

bool clang::driver::performELFWrapping(const std::string &InputELF,
                                const std::string &OutputPath,
                                const std::string &TargetTriple,
                                const std::string &ClangPath,
                                const std::string &Sysroot,
                                bool DebugMode) {
  // 1. 读取原始 ELF 文件
  std::ifstream in(InputELF, std::ios::binary | std::ios::ate);
  if (!in.is_open()) {
    errs() << "Error: [irobf-linker] Cannot open input ELF: " << InputELF << "\n";
    return false;
  }
  size_t file_size = in.tellg();
  in.seekg(0, std::ios::beg);

  std::vector<uint8_t> elf_data(file_size);
  if (!in.read(reinterpret_cast<char *>(elf_data.data()), file_size)) {
    errs() << "Error: [irobf-linker] Cannot read input ELF\n";
    return false;
  }
  in.close();

  // 验证 ELF 魔数
  if (elf_data.size() < 4 || elf_data[0] != 0x7f || elf_data[1] != 'E' ||
      elf_data[2] != 'L' || elf_data[3] != 'F') {
    errs() << "Warning: [irobf-linker] Input is not a valid ELF, skipping wrapper\n";
    // 不是 ELF，直接复制原文件
    sys::fs::copy_file(InputELF, OutputPath);
    return true;
  }

  if (DebugMode) outs() << "[irobf-linker] Wrapping ELF: " << file_size << " bytes\n";

  // 获取 clang 所在目录
  SmallString<128> clangDir;
  {
    SmallString<128> absClangPath(ClangPath);
    sys::fs::make_absolute(absClangPath);
    clangDir = sys::path::parent_path(absClangPath);
  }

  // 使用 llvm-strip 剥离符号表
  SmallString<256> llvmStripPath;
  sys::path::append(llvmStripPath, clangDir, "llvm-strip");
#ifdef _WIN32
  sys::path::replace_extension(llvmStripPath, "exe");
#endif
  if (sys::fs::exists(llvmStripPath)) {
    // 创建临时文件用于存储剥离符号后的 ELF
    SmallString<256> strippedPath(clangDir);
    std::string strippedName = (Twine(".linker_stripped_") +
                                Twine(sys::Process::getProcessId()) + "_" +
                                Twine(sys::path::filename(OutputPath)))
                                   .str();
    sys::path::append(strippedPath, strippedName);
    
    SmallVector<StringRef, 8> stripArgs;
    stripArgs.push_back(llvmStripPath);
    stripArgs.push_back("--strip-unneeded");
    stripArgs.push_back("-o");
    stripArgs.push_back(strippedPath);
    stripArgs.push_back(InputELF);
    
    std::string stripErrMsg;
    int stripRet = sys::ExecuteAndWait(llvmStripPath, stripArgs, {}, {}, 0, 0, &stripErrMsg);
    if (stripRet == 0) {
      // 重新读取剥离符号后的文件
      std::ifstream strippedFile(std::string(strippedPath.str()));
      if (strippedFile.is_open()) {
        strippedFile.seekg(0, std::ios::end);
        file_size = strippedFile.tellg();
        strippedFile.seekg(0, std::ios::beg);
        elf_data.resize(file_size);
        strippedFile.read(reinterpret_cast<char *>(elf_data.data()), file_size);
        strippedFile.close();
        if (DebugMode) outs() << "[irobf-linker] Stripped symbols, new size: " << file_size << " bytes\n";
      }
      sys::fs::remove(strippedPath);
    } else {
      if (DebugMode) outs() << "[irobf-linker] Warning: llvm-strip failed, using original ELF\n";
    }
  }

  // 2. 生成随机密钥并加密
  uint8_t key[32], nonce[12];
  generate_random_key(key, nonce);

  // 从 clang 同目录的 .linker_env_key[.<tag>] 文件读取密钥（由 EnvCheck Pass 生成）
  SmallString<256> linkerKeyPath;
  std::string linkerKeyFileName = ".linker_env_key";
  if (auto keyTag = sys::Process::GetEnv("IROBF_KEY_TAG"))
    linkerKeyFileName += "." + *keyTag;
  sys::path::append(linkerKeyPath, clangDir, linkerKeyFileName);
  std::string linkerKeyPathStr = std::string(linkerKeyPath.str());
  std::string env_key(32, '\0');
  {
    std::ifstream keyFile(linkerKeyPathStr);
    if (keyFile.is_open()) {
      keyFile.read(&env_key[0], 32);
      keyFile.close();
      if (DebugMode) outs() << "[irobf-linker] Read key from " << linkerKeyPath << ": " << env_key << "\n";
    } else {
      // 如果文件不存在，生成随机密钥
      if (DebugMode) outs() << "[irobf-linker] Warning: " << linkerKeyPath << " not found, generating random key\n";
      std::random_device rd;
      std::mt19937 gen(rd());
      std::uniform_int_distribution<int> dist(0, 15);
      const char hex[] = "0123456789abcdef";
      for (int i = 0; i < 32; i++)
        env_key[i] = hex[dist(gen)];
    }
  }

  std::vector<uint8_t> encrypted_data(file_size);
  chacha20_encrypt(elf_data.data(), file_size, key, nonce, encrypted_data.data());

  // 3. 创建临时目录
  SmallString<128> tmp_dir;
  std::error_code EC = sys::fs::createUniqueDirectory("elf-wrapper", tmp_dir);
  if (EC) {
    errs() << "Error: [irobf-linker] Cannot create temp directory: " << EC.message() << "\n";
    return false;
  }

  std::string payload_h_path = (tmp_dir + "/payload.h").str();
  std::string loader_cpp_path = (tmp_dir + "/loader.cpp").str();
  std::string loader_asm_path = (tmp_dir + "/loader.S").str();
  std::string wrapped_elf_path = (tmp_dir + "/wrapped.elf").str();
  bool useAsmTrampoline = StringRef(TargetTriple).starts_with("aarch64");

  // 4. 生成 payload.h / loader.cpp / loader.S
  if (!generatePayloadH(payload_h_path, encrypted_data.data(), file_size, key, nonce, env_key)) {
    sys::fs::remove_directories(tmp_dir);
    return false;
  }

  if (!generateLoaderCpp(loader_cpp_path, DebugMode, useAsmTrampoline)) {
    sys::fs::remove_directories(tmp_dir);
    return false;
  }

  if (useAsmTrampoline &&
      !generateLoaderAsm(loader_asm_path, TargetTriple)) {
    sys::fs::remove_directories(tmp_dir);
    return false;
  }

  // 规范化路径（去掉 .. 等，统一使用绝对路径）
  std::string normalized_clang, normalized_sysroot;
  SmallString<128> abs_path(ClangPath);
  sys::fs::make_absolute(abs_path);
  sys::path::remove_dots(abs_path, /*remove_dot_dot=*/true);
  normalized_clang = std::string(abs_path);

  if (!Sysroot.empty()) {
    abs_path = Sysroot;
    sys::fs::make_absolute(abs_path);
    sys::path::remove_dots(abs_path, /*remove_dot_dot=*/true);
    normalized_sysroot = std::string(abs_path);
  }

  // 5. 编译壳程序 - 调用 clang 自身，最高强度混淆
  std::string compile_cmd =
      "\"" + normalized_clang + "\""
      + " -target " + TargetTriple;
  if (!normalized_sysroot.empty())
    compile_cmd += " --sysroot=\"" + normalized_sysroot + "\"";
  compile_cmd += std::string(" -O2 -std=c++17 -fno-exceptions -frtti -fPIE -pie");
  if (useAsmTrampoline)
    compile_cmd += " -nostartfiles -Wl,-e,_start";
  compile_cmd += " -mllvm -irobf";
  compile_cmd += " -mllvm -irobf-indbr -mllvm -level-indbr=3";
  compile_cmd += " -mllvm -irobf-icall -mllvm -level-icall=3";
  compile_cmd += " -mllvm -irobf-fla -mllvm -level-fla=3";
  compile_cmd += " -mllvm -irobf-indgv -mllvm -level-indgv=3";
  compile_cmd += " -mllvm -irobf-cse";
  compile_cmd += " -mllvm -irobf-cie -mllvm -level-cie=3";
  compile_cmd += " -mllvm -irobf-cfe -mllvm -level-cfe=3";
  compile_cmd += " -mllvm -irobf-rtti";
  compile_cmd += " -mllvm -irobf-ldpreload";
  compile_cmd += " -mllvm -irobf-usb";
  compile_cmd += " -mllvm -irobf-time";
  compile_cmd += " -mllvm -irobf-syscall";
  compile_cmd += " -lm -ldl -llog";
  compile_cmd += " -o \"" + wrapped_elf_path + "\"";
  compile_cmd += " \"" + loader_cpp_path + "\"";
  if (useAsmTrampoline)
    compile_cmd += " \"" + loader_asm_path + "\"";
  compile_cmd += " -I\"" + std::string(tmp_dir.str()) + "\"";

  if (DebugMode) outs() << "[irobf-linker] Compiling wrapper with max obfuscation...\n";

  // 使用 llvm::sys::ExecuteAndWait 替代 system()，避免 Windows cmd.exe 路径问题
  SmallVector<StringRef, 64> argv;
  argv.push_back(normalized_clang);
  argv.push_back("-target");
  argv.push_back(TargetTriple);
  if (!normalized_sysroot.empty()) {
    argv.push_back("--sysroot");
    argv.push_back(normalized_sysroot);
  }
  argv.push_back("-O2");
  argv.push_back("-std=c++17");
  argv.push_back("-fno-exceptions");
  argv.push_back("-frtti");
  argv.push_back("-fPIE");
  argv.push_back("-pie");
  if (useAsmTrampoline) {
    argv.push_back("-nostartfiles");
    argv.push_back("-Wl,-e,_start");
  }
  argv.push_back("-mllvm"); argv.push_back("-irobf");
  argv.push_back("-mllvm"); argv.push_back("-irobf-indbr");
  argv.push_back("-mllvm"); argv.push_back("-level-indbr=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-icall");
  argv.push_back("-mllvm"); argv.push_back("-level-icall=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-fla");
  argv.push_back("-mllvm"); argv.push_back("-level-fla=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-indgv");
  argv.push_back("-mllvm"); argv.push_back("-level-indgv=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-cse");
  argv.push_back("-mllvm"); argv.push_back("-irobf-cie");
  argv.push_back("-mllvm"); argv.push_back("-level-cie=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-cfe");
  argv.push_back("-mllvm"); argv.push_back("-level-cfe=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-rtti");
  argv.push_back("-mllvm"); argv.push_back("-irobf-ldpreload");
  argv.push_back("-mllvm"); argv.push_back("-irobf-usb");
  argv.push_back("-mllvm"); argv.push_back("-irobf-time");
  argv.push_back("-mllvm"); argv.push_back("-irobf-syscall");
  argv.push_back("-lm");
  argv.push_back("-ldl");
  argv.push_back("-llog");
  argv.push_back("-o");
  argv.push_back(wrapped_elf_path);
  argv.push_back(loader_cpp_path);
  if (useAsmTrampoline)
    argv.push_back(loader_asm_path);
  std::string include_arg = "-I" + std::string(tmp_dir.str());
  argv.push_back(include_arg);

  std::string errMsg;
  int ret = sys::ExecuteAndWait(normalized_clang, argv, {},
                                 {}, 0, 0, &errMsg);

  if (ret != 0) {
    errs() << "Error: [irobf-linker] Wrapper compilation failed (code: " << ret << ")";
    if (!errMsg.empty()) errs() << ": " << errMsg;
    errs() << "\n";
    sys::fs::remove_directories(tmp_dir);
    return false;
  }

  // 6. 复制到输出路径
  EC = sys::fs::copy_file(wrapped_elf_path, OutputPath);
  if (EC) {
    errs() << "Error: [irobf-linker] Cannot copy to output: " << EC.message() << "\n";
    sys::fs::remove_directories(tmp_dir);
    return false;
  }

  // 设置可执行权限
  sys::fs::setPermissions(OutputPath, sys::fs::perms::all_read |
                                          sys::fs::perms::all_write |
                                          sys::fs::perms::owner_exe |
                                          sys::fs::perms::group_exe |
                                          sys::fs::perms::others_exe);

  // 清理临时文件
  sys::fs::remove_directories(tmp_dir);
  // 删除链接器输出的临时文件
  sys::fs::remove(InputELF);
  // 删除密钥文件
  sys::fs::remove(linkerKeyPath);

  if (DebugMode) outs() << "[irobf-linker] Done! Wrapped ELF: " << OutputPath << "\n";
  return true;
}

// ============================================================================
// Base64 编码
// ============================================================================

static const char base64_table[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

static std::string base64_encode(const uint8_t *data, size_t len) {
  std::string result;
  result.reserve((len + 2) / 3 * 4);
  for (size_t i = 0; i < len; i += 3) {
    uint32_t n = (uint32_t)data[i] << 16;
    if (i + 1 < len) n |= (uint32_t)data[i + 1] << 8;
    if (i + 2 < len) n |= (uint32_t)data[i + 2];
    result.push_back(base64_table[(n >> 18) & 0x3F]);
    result.push_back(base64_table[(n >> 12) & 0x3F]);
    result.push_back((i + 1 < len) ? base64_table[(n >> 6) & 0x3F] : '=');
    result.push_back((i + 2 < len) ? base64_table[n & 0x3F] : '=');
  }
  return result;
}

// ============================================================================
// gzip 压缩（使用 LLVM 内置 zlib 支持）
// ============================================================================

static bool gzip_compress(const uint8_t *input, size_t input_len,
                          std::vector<uint8_t> &output) {
  if (!compression::zlib::isAvailable()) {
    errs() << "Error: [irobf-gz] zlib not available in this build\n";
    return false;
  }
  SmallVector<uint8_t, 0> compressed;
  compression::zlib::compress(ArrayRef<uint8_t>(input, input_len),
                              compressed,
                              compression::zlib::BestSizeCompression);
  output.assign(compressed.begin(), compressed.end());
  return true;
}

// ============================================================================
// 执行 gzip+base64 压缩壳（生成 shell 脚本）
// ============================================================================

bool clang::driver::performGzWrapping(const std::string &InputELF,
                                      const std::string &OutputPath,
                                      const std::string &TargetTriple,
                                      const std::string &ClangPath,
                                      const std::string &Sysroot,
                                      bool DebugMode) {
  // 1. 读取输入 ELF 文件
  std::ifstream in(InputELF, std::ios::binary | std::ios::ate);
  if (!in.is_open()) {
    errs() << "Error: [irobf-gz] Cannot open input ELF: " << InputELF << "\n";
    return false;
  }
  size_t file_size = in.tellg();
  in.seekg(0, std::ios::beg);

  std::vector<uint8_t> elf_data(file_size);
  if (!in.read(reinterpret_cast<char *>(elf_data.data()), file_size)) {
    errs() << "Error: [irobf-gz] Cannot read input ELF\n";
    return false;
  }
  in.close();

  // 验证 ELF 魔数
  if (elf_data.size() < 4 || elf_data[0] != 0x7f || elf_data[1] != 'E' ||
      elf_data[2] != 'L' || elf_data[3] != 'F') {
    errs() << "Warning: [irobf-gz] Input is not a valid ELF, skipping wrapper\n";
    sys::fs::copy_file(InputELF, OutputPath);
    return true;
  }

  if (DebugMode) outs() << "[irobf-gz] Compressing ELF: " << file_size << " bytes\n";

  // 获取 clang 所在目录
  SmallString<128> clangDir;
  {
    SmallString<128> absClangPath(ClangPath);
    sys::fs::make_absolute(absClangPath);
    clangDir = sys::path::parent_path(absClangPath);
  }

  // 使用 llvm-strip 剥离符号表
  SmallString<256> llvmStripPath;
  sys::path::append(llvmStripPath, clangDir, "llvm-strip");
#ifdef _WIN32
  sys::path::replace_extension(llvmStripPath, "exe");
#endif
  if (sys::fs::exists(llvmStripPath)) {
    // 创建临时文件用于存储剥离符号后的 ELF
    SmallString<256> strippedPath;
    sys::path::append(strippedPath, clangDir, ".gz_stripped");
    
    SmallVector<StringRef, 8> stripArgs;
    stripArgs.push_back(llvmStripPath);
    stripArgs.push_back("--strip-unneeded");
    stripArgs.push_back("-o");
    stripArgs.push_back(strippedPath);
    stripArgs.push_back(InputELF);
    
    std::string stripErrMsg;
    int stripRet = sys::ExecuteAndWait(llvmStripPath, stripArgs, {}, {}, 0, 0, &stripErrMsg);
    if (stripRet == 0) {
      // 重新读取剥离符号后的文件
      std::ifstream strippedFile(std::string(strippedPath.str()));
      if (strippedFile.is_open()) {
        strippedFile.seekg(0, std::ios::end);
        file_size = strippedFile.tellg();
        strippedFile.seekg(0, std::ios::beg);
        elf_data.resize(file_size);
        strippedFile.read(reinterpret_cast<char *>(elf_data.data()), file_size);
        strippedFile.close();
        if (DebugMode) outs() << "[irobf-gz] Stripped symbols, new size: " << file_size << " bytes\n";
      }
      sys::fs::remove(strippedPath);
    } else {
      if (DebugMode) outs() << "[irobf-gz] Warning: llvm-strip failed, using original ELF\n";
    }
  }

  // 从 clang 同目录的 .gz_env_key[.<tag>] 文件读取密钥（由 GzEnvCheck Pass 生成）
  SmallString<256> gzKeyPath;
  std::string gzKeyFileName = ".gz_env_key";
  if (auto keyTag = sys::Process::GetEnv("IROBF_KEY_TAG"))
    gzKeyFileName += "." + *keyTag;
  sys::path::append(gzKeyPath, clangDir, gzKeyFileName);
  std::string gzKeyPathStr = std::string(gzKeyPath.str());
  std::string gz_env_key(32, '\0');
  {
    std::ifstream keyFile(gzKeyPathStr);
    if (keyFile.is_open()) {
      keyFile.read(&gz_env_key[0], 32);
      keyFile.close();
      if (DebugMode) outs() << "[irobf-gz] Read key from " << gzKeyPath << ": " << gz_env_key << "\n";
    } else {
      // 如果文件不存在，生成随机密钥
      if (DebugMode) outs() << "[irobf-gz] Warning: " << gzKeyPath << " not found, generating random key\n";
      std::random_device rd;
      std::mt19937 gen(rd());
      std::uniform_int_distribution<int> dist(0, 15);
      const char hex[] = "0123456789abcdef";
      for (int i = 0; i < 32; i++)
        gz_env_key[i] = hex[dist(gen)];
    }
  }

  // 3. base64 编码（跳过 gzip 压缩，直接编码原始 ELF）
  std::string b64_data = base64_encode(elf_data.data(), file_size);
  if (DebugMode) outs() << "[irobf-gz] Base64 encoded: " << b64_data.size() << " bytes\n";

  size_t hidden_pos = b64_data.size() / 2;
  std::string b64_prefix = b64_data.substr(0, hidden_pos);
  std::string b64_suffix = b64_data.substr(hidden_pos);

  // 4. 生成 shell 脚本
  std::error_code EC;
  raw_fd_ostream OS(OutputPath, EC, sys::fs::OF_None);
  if (EC) {
    errs() << "Error: [irobf-gz] Cannot write output: " << EC.message() << "\n";
    return false;
  }

  // Shell 脚本头部
  OS << "#!/system/bin/sh\n";
  OS << "# By.wsq520a 给小辈一个面子，别破解了，相信大牛你的实力了\n";
  constexpr size_t kShellChunkSize = 512;
  auto emitShellAppend = [&](const std::string &Data) {
    for (size_t I = 0; I < Data.size(); I += kShellChunkSize) {
      OS << "echo -n '" << Data.substr(I, kShellChunkSize) << "'>>\"$F\";";
    }
  };

  OS << "T=/data/local/tmp/.gz_$$;F=\"$T.b64\";trap 'rm -f \"$T\" \"$F\"' EXIT;:>\"$F\";";
  emitShellAppend(b64_prefix);
  OS << "K='" << gz_env_key << "';export lc_gz=\"$K\";unset K;";
  emitShellAppend(b64_suffix);
  OS << "base64 -d<\"$F\">\"$T\" 2>/dev/null;chmod 700 \"$T\";"
        "\"$T\" \"$@\";R=$?;rm -f \"$T\" \"$F\";exit $R\n";

  OS.flush();

  // 设置可执行权限
  sys::fs::setPermissions(OutputPath, sys::fs::perms::all_read |
                                          sys::fs::perms::all_write |
                                          sys::fs::perms::owner_exe |
                                          sys::fs::perms::group_exe |
                                          sys::fs::perms::others_exe);

  // 删除输入文件
  sys::fs::remove(InputELF);
  // 删除密钥文件
  sys::fs::remove(gzKeyPath);

  if (DebugMode) outs() << "[irobf-gz] Done! Shell wrapper: " << OutputPath << "\n";
  return true;
}
